# Generated by Django 3.2.9 on 2021-11-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamperson',
            name='position',
            field=models.CharField(choices=[('left', 'left'), ('right', 'right')], default='right', max_length=200),
        ),
    ]
