# Generated by Django 3.2.9 on 2021-11-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_teamperson_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolioContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('projectDate', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=False)),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.AlterField(
            model_name='teamperson',
            name='position',
            field=models.CharField(choices=[('left', 'left'), ('right', 'right')], default='left', max_length=200),
        ),
        migrations.AlterField(
            model_name='teamperson',
            name='text',
            field=models.TextField(max_length=340),
        ),
    ]
